services:
  backend:
    image: ghcr.io/p4inty/web-tech-prototype:main
    ports:
      - "1337:8080"
    restart: "always"
    networks:
      - "backend.network"
    volumes:
      - "/media:/public/upload:rw"

  frontend:
    image: ghcr.io/p4inty/web-tech-prototype-frontend:main
    ports:
      - "80:80"
    restart: "always"
    networks:
      - "backend.network"

networks:
  backend.network:
