FROM node:18-alpine as build

WORKDIR /app

COPY ./frontend .

ENV VITE_API_PORT=:1337
ENV VITE_API_URL=https://backend-ihspbbar4q-ew.a.run.app/uploads

RUN npm install && npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html