services:
  backend:
    image: ghcr.io/p4inty/web-tech-prototype:main
    ports:
      - "8080:8080"
    restart: "always"
    networks:
      - "backend.network"

  frontend:
    image: ghcr.io/p4inty/web-tech-prototype-frontend:main
    ports:
      - "80:80"
    networks:
      - "backend.network"

networks:
  backend.network:
